### ISSUE TITLE
Usage of Driver, Description, Gazebo Simulation on ROS2

### ISSUE THREAD

**Issue by ghost** [UniversalRobots/Universal_Robots_ROS2_Driver#698] opened 2023-05-29 23:42 UTC
Hey,
I have installed Universal_Robots_ROS2_Driver using binary builds. 

1. I checked that [ursim](https://hub.docker.com/r/universalrobots/ursim_e-series) works based on docker. But unable to run [Usage with official UR simulator](https://docs.ros.org/en/ros2_packages/humble/api/ur_robot_driver/usage.html#usage-with-official-ur-simulator) on ros2 commands. Could I get explanation what's wrong on this?
2. For full simulation on Gazebo(I don't have real robot), should I install [Description](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description) [Gazebo Simulation](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation) also or just Driver is enough?
3. As there is no actual gripper on URbot series, I am planning to add customized gripper on it, convert it into URDF, and want to simulate it onto Gazebo, ursim for object detection. Is there a documentation or tutorial how to do it?

Thanks in advance.

**Comment by segapss** [comment] 2023-05-31 14:46
@firesurfer Thanks. Are you referring to [this](https://github.com/ros-controls/ros2_control)? Then apart from Gazebo, do you think it is wise to rely on Universal_Robots_ROS2_Driver and URSIM for it? I think [Articulated Robotics](https://www.youtube.com/watch?v=J02jEKawE5U) is giving a good solution. Then you sure that ROS2 control can be operated without real robot?

**Comment by firesurfer** [comment] 2023-06-01 12:10
@segapss 

So either way you are doing this. You will / want to always use ros2control somewhere in between. If you specify `use_fake_hardware=true`  ros2control will initiate a simple mockinterface (which is enough if you want to test position controlled commands).

We tried some time ago to setup everything with gazebo in order to test force controlled algorithms but had a hard time to get everything running stable. We decided in the end not to use it. 

Regarding point 3. You can use the robotiq grippers fairly easy on the URs.

**Comment by segapss** [comment] 2023-06-01 12:24
@firesurfer Thanks. Then I will need to rely on ros2control more.

**Comment by sillkjc** [comment] 2023-06-05 10:08
My team has written a Gazebo plugin that watches ./joint_states and sets the gazebo robot joint angles accordingly. We run ur_sim in the loop with use_fake_hardware false, so the simulated code does not know it is simulated.

We will be publishing this on our github, but if there is interest to accelerate this let me know.

**Comment by PietroDrd** [comment] 2023-11-02 16:17
@sillkjc Hi!
Is there any update about your Gazebo plugin? Thanks!

**Comment by brta-jc** [comment] 2023-11-10 01:45
> @sillkjc Hi! Is there any update about your Gazebo plugin? Thanks!
Hi PietroDrd, I've pushed it here, there is also a Noetic branch.
https://github.com/Boeing/gazebo_set_joint_positions_plugin/tree/humble

We are currently in queue to get ros-humble-boeing-* packages added to apt so they can easily be pulled as debs.  As we get the flow down we'll be releasing more packages.

**Comment by VinDp** [comment] 2024-07-03 09:32
Since the issue is pretty old and everything seems to be solved, I will close it.
It could be helpful to add that Gazebo simulation depends only on the [description](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description) package and the [moveit_config](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/main/ur_moveit_config) (part of the driver repo). Also we now have an [updated documentation](https://docs.universal-robots.com/Universal_Robots_ROS_Documentation/doc/ur_simulation_gz/ur_simulation_gz/doc/index.html) for GZ for Rolling and Jazzy.

**Closed by VinDp** 2024-07-03 09:32 UTC
