### ISSUE TITLE
Joint 'shoulder_pan_joint' has 9765923333140350858 command interfaces found. 2 expected.

### ISSUE THREAD

**Issue by T2FF** [UniversalRobots/Universal_Robots_ROS2_Driver#320] opened 2022-03-29 14:33 UTC
Hi together,

I'm trying to run ROS2 in combination with URSim. ROS2 is normally installed on my Ubuntu 20.04 machine and URSim is running as [Dockerimage](https://hub.docker.com/r/universalrobots/ursim_e-series).

I start the docker image with installed URCaps with the following command:
`sudo docker run --rm -it -p 5900:5900 -p 6080:6080 -p 50002:50002 -p29999:29999 -e ROBOT_MODEL=UR5e c42dffcdd674`

Then I start ROS2 with the following command:
`ros2 launch ur_bringup ur_control.launch.py ur_type:=ur5e robot_ip:=127.0.0.1 launch_rviz:=false`

The first error-message I get is this one:
`[ur_ros2_control_node-1] [FATAL] [1648562435.627828426] [URPositionHardwareInterface]: Joint 'shoulder_pan_joint' has 9765923333140350858 command interfaces found. 2 expected.`

and many more will follow.

Complete Output:

```diff
ros2 launch ur_bringup ur_control.launch.py ur_type:=ur5e robot_ip:=127.0.0.1 launch_rviz:=false

[INFO] [launch]: All log files can be found below /home/workstation/.ros/log/2022-03-29-16-17-35-386699-workstation-System-Product-Name-33609
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [dashboard_client-2]: process started with pid [33615]
[INFO] [ur_ros2_control_node-1]: process started with pid [33613]
[INFO] [robot_state_publisher-3]: process started with pid [33617]
[INFO] [spawner-4]: process started with pid [33619]
[INFO] [spawner-5]: process started with pid [33621]
[INFO] [spawner-6]: process started with pid [33623]
[INFO] [spawner-7]: process started with pid [33625]
[INFO] [spawner-8]: process started with pid [33627]
[INFO] [spawner-9]: process started with pid [33629]
[robot_state_publisher-3] Link base_link had 2 children
[robot_state_publisher-3] Link base had 0 children
[robot_state_publisher-3] Link base_link_inertia had 1 children
[robot_state_publisher-3] Link shoulder_link had 1 children
[robot_state_publisher-3] Link upper_arm_link had 1 children
[robot_state_publisher-3] Link forearm_link had 1 children
[robot_state_publisher-3] Link wrist_1_link had 1 children
[robot_state_publisher-3] Link wrist_2_link had 1 children
[robot_state_publisher-3] Link wrist_3_link had 2 children
[robot_state_publisher-3] Link flange had 1 children
[robot_state_publisher-3] Link tool0 had 0 children
[robot_state_publisher-3] Link ft_frame had 0 children
[robot_state_publisher-3] [INFO] [1648563456.627984513] [robot_state_publisher]: got segment base
[robot_state_publisher-3] [INFO] [1648563456.628051389] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1648563456.628058465] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-3] [INFO] [1648563456.628063102] [robot_state_publisher]: got segment flange
[robot_state_publisher-3] [INFO] [1648563456.628067283] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-3] [INFO] [1648563456.628071468] [robot_state_publisher]: got segment ft_frame
[robot_state_publisher-3] [INFO] [1648563456.628075561] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-3] [INFO] [1648563456.628079658] [robot_state_publisher]: got segment tool0
[robot_state_publisher-3] [INFO] [1648563456.628083589] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-3] [INFO] [1648563456.628087705] [robot_state_publisher]: got segment world
[robot_state_publisher-3] [INFO] [1648563456.628091712] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-3] [INFO] [1648563456.628095738] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-3] [INFO] [1648563456.628099673] [robot_state_publisher]: got segment wrist_3_link
-[ur_ros2_control_node-1] [FATAL] [1648563456.632742739] [URPositionHardwareInterface]: Joint 'shoulder_pan_joint' has 9765923333140350858 command interfaces found. 2 expected.
-[ur_ros2_control_node-1] terminate called after throwing an instance of 'std::runtime_error'
-[ur_ros2_control_node-1]   what():  Failed to initialize 'ur5e'
-[ERROR] [ur_ros2_control_node-1]: process has died [pid 33613, exit code -6, cmd '/home/workstation/workspace/ros_ur_driver/install/ur_robot_driver/lib/ur_robot_driver/ur_ros2_control_node --ros-args --params-file /tmp/launch_params_akn88lnw --params-file /home/workstation/workspace/ros_ur_driver/install/ur_bringup/share/ur_bringup/config/ur5e_update_rate.yaml --params-file /home/workstation/workspace/ros_ur_driver/install/ur_bringup/share/ur_bringup/config/ur_controllers.yaml'].
[spawner-9] [INFO] [1648563456.886327784] [spawner_scaled_joint_trajectory_controller]: Waiting for /controller_manager services
[spawner-5] [INFO] [1648563456.889668191] [spawner_io_and_status_controller]: Waiting for /controller_manager services
[spawner-4] [INFO] [1648563456.893150753] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner-7] [INFO] [1648563456.894236077] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[spawner-6] [INFO] [1648563456.895837876] [spawner_speed_scaling_state_broadcaster]: Waiting for /controller_manager services
[spawner-8] [INFO] [1648563456.926657686] [spawner_forward_position_controller]: Waiting for /controller_manager services
[spawner-9] [INFO] [1648563458.900526339] [spawner_scaled_joint_trajectory_controller]: Waiting for /controller_manager services
[spawner-5] [INFO] [1648563458.903997293] [spawner_io_and_status_controller]: Waiting for /controller_manager services
[spawner-4] [INFO] [1648563458.906694242] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner-7] [INFO] [1648563458.907983437] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[spawner-6] [INFO] [1648563458.908871027] [spawner_speed_scaling_state_broadcaster]: Waiting for /controller_manager services
[spawner-8] [INFO] [1648563458.940693515] [spawner_forward_position_controller]: Waiting for /controller_manager services
[spawner-9] [INFO] [1648563460.915079984] [spawner_scaled_joint_trajectory_controller]: Waiting for /controller_manager services
[spawner-5] [INFO] [1648563460.917965698] [spawner_io_and_status_controller]: Waiting for /controller_manager services
[spawner-4] [INFO] [1648563460.920085357] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner-7] [INFO] [1648563460.921884718] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[spawner-6] [INFO] [1648563460.922673200] [spawner_speed_scaling_state_broadcaster]: Waiting for /controller_manager services
[spawner-8] [INFO] [1648563460.955214631] [spawner_forward_position_controller]: Waiting for /controller_manager services
[spawner-9] [INFO] [1648563462.929412264] [spawner_scaled_joint_trajectory_controller]: Waiting for /controller_manager services
[spawner-5] [INFO] [1648563462.931654124] [spawner_io_and_status_controller]: Waiting for /controller_manager services
[spawner-4] [INFO] [1648563462.932760345] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner-7] [INFO] [1648563462.935538990] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[spawner-6] [INFO] [1648563462.936576723] [spawner_speed_scaling_state_broadcaster]: Waiting for /controller_manager services
[spawner-8] [INFO] [1648563462.969188511] [spawner_forward_position_controller]: Waiting for /controller_manager services
[spawner-9] [INFO] [1648563464.943971656] [spawner_scaled_joint_trajectory_controller]: Waiting for /controller_manager services
[spawner-5] [INFO] [1648563464.944821987] [spawner_io_and_status_controller]: Waiting for /controller_manager services
[spawner-4] [INFO] [1648563464.946186716] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner-7] [INFO] [1648563464.948876344] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[spawner-6] [INFO] [1648563464.949819301] [spawner_speed_scaling_state_broadcaster]: Waiting for /controller_manager services
[spawner-8] [INFO] [1648563464.982915475] [spawner_forward_position_controller]: Waiting for /controller_manager services
-[spawner-9] [ERROR] [1648563466.957946052] [spawner_scaled_joint_trajectory_controller]: Controller manager not available
-[spawner-5] [ERROR] [1648563466.958330257] [spawner_io_and_status_controller]: Controller manager not available
-[spawner-4] [ERROR] [1648563466.960107211] [spawner_joint_state_broadcaster]: Controller manager not available
-[spawner-7] [ERROR] [1648563466.962193442] [spawner_force_torque_sensor_broadcaster]: Controller manager not available
-[spawner-6] [ERROR] [1648563466.963140978] [spawner_speed_scaling_state_broadcaster]: Controller manager not available
-[spawner-8] [ERROR] [1648563466.996962150] [spawner_forward_position_controller]: Controller manager not available
-[ERROR] [spawner-9]: process has died [pid 33629, exit code 1, cmd '/home/workstation/workspace/ros_ur_driver/install/controller_manager/lib/controller_manager/spawner scaled_joint_trajectory_controller -c /controller_manager --ros-args'].
-[ERROR] [spawner-7]: process has died [pid 33625, exit code 1, cmd '/home/workstation/workspace/ros_ur_driver/install/controller_manager/lib/controller_manager/spawner force_torque_sensor_broadcaster --controller-manager /controller_manager --ros-args'].
-[ERROR] [spawner-6]: process has died [pid 33623, exit code 1, cmd '/home/workstation/workspace/ros_ur_driver/install/controller_manager/lib/controller_manager/spawner speed_scaling_state_broadcaster --controller-manager /controller_manager --ros-args'].
-[ERROR] [spawner-5]: process has died [pid 33621, exit code 1, cmd '/home/workstation/workspace/ros_ur_driver/install/controller_manager/lib/controller_manager/spawner io_and_status_controller -c /controller_manager --ros-args'].
-[ERROR] [spawner-4]: process has died [pid 33619, exit code 1, cmd '/home/workstation/workspace/ros_ur_driver/install/controller_manager/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
-[ERROR] [spawner-8]: process has died [pid 33627, exit code 1, cmd '/home/workstation/workspace/ros_ur_driver/install/controller_manager/lib/controller_manager/spawner forward_position_controller -c /controller_manager --stopped --ros-args'].
```

When I'm using the  `use_fake_hardware:=true` attribute, everything works fine.

Is this a bug or am I doing something wrong?

**Comment by fmauch** [comment] 2022-03-30 18:56
my bad... the correct command should be 
```
for repo in `find . -name ".git" -type d | sed 's/\/.git//' | sort`; do echo "=== $repo ==="; pushd $repo; git rev-parse --abbrev-ref HEAD; git rev-parse --short HEAD; popd ; done
```

The output should be somethin like this:
```
=== ./Universal_Robots_Client_Library ===
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src/Universal_Robots_Client_Library ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
master
8f20b42
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
=== ./Universal_Robots_ROS2_Description ===
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src/Universal_Robots_ROS2_Description ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
ros2
a584902
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
=== ./Universal_Robots_ROS2_Driver ===
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src/Universal_Robots_ROS2_Driver ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
main
4de4bb3
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
=== ./Universal_Robots_ROS2_Gazebo_Simulation ===
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src/Universal_Robots_ROS2_Gazebo_Simulation ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
ros2
708c48b
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
=== ./ur_msgs ===
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src/ur_msgs ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
ros2
7ea5b71
~/robot_folders/checkout/ur_ros2_galactic/colcon_ws/src ~/robot_folders/checkout/ur_ros2_galactic/colcon_ws ~
```

**Comment by fmauch** [comment] 2022-03-30 19:03
Closing this as it is a Duplicate of #317. Let's continue there.

**Comment by fmauch** [comment] 2022-03-30 19:05
Duplicate of #317

**Closed** 2022-03-30 19:05 UTC
